version: '3.8'

services:
  bot:
    build: .
    volumes:
      - .:/app
    restart: always
    environment:
      - URL_DB=postgresql+asyncpg://nikolay:1234@postgres:5432/bot_db
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: nikolay
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: diploma_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
