version: '3.8'

services:
  bot:
    build: .
    volumes:
      - ./database:/app/database
      - ./TG:/app/TG
      - ./.env:/app/.env
      - ./config.py:/app/config.py
      - ./main_bot.py:/app/main_bot.py
    restart: always
    environment:
      - DATABASE_URL=postgresql+asyncpg://nikolay:1234@postgres:5432/diploma_db
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: nikolay
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: diploma_db
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
